// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/squadcastv1/models/components"
)

type CommunicationCardsGetAllCommunicationCardRequest struct {
	IncidentID string `pathParam:"style=simple,explode=false,name=IncidentId"`
}

func (o *CommunicationCardsGetAllCommunicationCardRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

// CommunicationCardsGetAllCommunicationCardResponseBody - The request has succeeded.
type CommunicationCardsGetAllCommunicationCardResponseBody struct {
	Data []components.V3IncidentsCommunicationCardsCommunicationCardResponse `json:"data"`
}

func (o *CommunicationCardsGetAllCommunicationCardResponseBody) GetData() []components.V3IncidentsCommunicationCardsCommunicationCardResponse {
	if o == nil {
		return []components.V3IncidentsCommunicationCardsCommunicationCardResponse{}
	}
	return o.Data
}

type CommunicationCardsGetAllCommunicationCardResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *CommunicationCardsGetAllCommunicationCardResponseBody
}

func (o *CommunicationCardsGetAllCommunicationCardResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CommunicationCardsGetAllCommunicationCardResponse) GetObject() *CommunicationCardsGetAllCommunicationCardResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
