// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type ComponentGroupsListComponentGroupsRequest struct {
	StatuspageID string `pathParam:"style=simple,explode=false,name=statuspageID"`
}

func (o *ComponentGroupsListComponentGroupsRequest) GetStatuspageID() string {
	if o == nil {
		return ""
	}
	return o.StatuspageID
}

// ComponentGroupsListComponentGroupsResponseBody - The request has succeeded.
type ComponentGroupsListComponentGroupsResponseBody struct {
	Data []components.V4StatusPagesComponentGroupsComponentGroupResponse `json:"data"`
}

func (o *ComponentGroupsListComponentGroupsResponseBody) GetData() []components.V4StatusPagesComponentGroupsComponentGroupResponse {
	if o == nil {
		return []components.V4StatusPagesComponentGroupsComponentGroupResponse{}
	}
	return o.Data
}

type ComponentGroupsListComponentGroupsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *ComponentGroupsListComponentGroupsResponseBody
}

func (o *ComponentGroupsListComponentGroupsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ComponentGroupsListComponentGroupsResponse) GetObject() *ComponentGroupsListComponentGroupsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
