// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type IncidentsReassignIncidentRequest struct {
	IncidentID                         string                                        `pathParam:"style=simple,explode=false,name=incidentID"`
	V3IncidentsReassignIncidentRequest components.V3IncidentsReassignIncidentRequest `request:"mediaType=application/json"`
}

func (o *IncidentsReassignIncidentRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

func (o *IncidentsReassignIncidentRequest) GetV3IncidentsReassignIncidentRequest() components.V3IncidentsReassignIncidentRequest {
	if o == nil {
		return components.V3IncidentsReassignIncidentRequest{}
	}
	return o.V3IncidentsReassignIncidentRequest
}

// IncidentsReassignIncidentResponseBody - The request has succeeded.
type IncidentsReassignIncidentResponseBody struct {
	Data string `json:"data"`
}

func (o *IncidentsReassignIncidentResponseBody) GetData() string {
	if o == nil {
		return ""
	}
	return o.Data
}

type IncidentsReassignIncidentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *IncidentsReassignIncidentResponseBody
}

func (o *IncidentsReassignIncidentResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *IncidentsReassignIncidentResponse) GetObject() *IncidentsReassignIncidentResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
