// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type PostmortemsUpdatePostmortemByIncidentRequest struct {
	IncidentID                                    string                                                   `pathParam:"style=simple,explode=false,name=incidentID"`
	V3IncidentsPostmortemsUpdatePostmortemRequest components.V3IncidentsPostmortemsUpdatePostmortemRequest `request:"mediaType=application/json"`
}

func (o *PostmortemsUpdatePostmortemByIncidentRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

func (o *PostmortemsUpdatePostmortemByIncidentRequest) GetV3IncidentsPostmortemsUpdatePostmortemRequest() components.V3IncidentsPostmortemsUpdatePostmortemRequest {
	if o == nil {
		return components.V3IncidentsPostmortemsUpdatePostmortemRequest{}
	}
	return o.V3IncidentsPostmortemsUpdatePostmortemRequest
}

// PostmortemsUpdatePostmortemByIncidentResponseBody - The request has succeeded.
type PostmortemsUpdatePostmortemByIncidentResponseBody struct {
	Data components.V3IncidentsPostmortemsPostmortemResponse `json:"data"`
}

func (o *PostmortemsUpdatePostmortemByIncidentResponseBody) GetData() components.V3IncidentsPostmortemsPostmortemResponse {
	if o == nil {
		return components.V3IncidentsPostmortemsPostmortemResponse{}
	}
	return o.Data
}

type PostmortemsUpdatePostmortemByIncidentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *PostmortemsUpdatePostmortemByIncidentResponseBody
}

func (o *PostmortemsUpdatePostmortemByIncidentResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostmortemsUpdatePostmortemByIncidentResponse) GetObject() *PostmortemsUpdatePostmortemByIncidentResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
