// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/squadcastv1/models/components"
)

type RotationsGetRotationParticipantsRequest struct {
	ScheduleID string `pathParam:"style=simple,explode=false,name=scheduleID"`
	RotationID string `pathParam:"style=simple,explode=false,name=rotationID"`
}

func (o *RotationsGetRotationParticipantsRequest) GetScheduleID() string {
	if o == nil {
		return ""
	}
	return o.ScheduleID
}

func (o *RotationsGetRotationParticipantsRequest) GetRotationID() string {
	if o == nil {
		return ""
	}
	return o.RotationID
}

// RotationsGetRotationParticipantsResponseBody - The request has succeeded.
type RotationsGetRotationParticipantsResponseBody struct {
	Data components.V4GetRotationParticipantsResponse `json:"data"`
}

func (o *RotationsGetRotationParticipantsResponseBody) GetData() components.V4GetRotationParticipantsResponse {
	if o == nil {
		return components.V4GetRotationParticipantsResponse{}
	}
	return o.Data
}

type RotationsGetRotationParticipantsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *RotationsGetRotationParticipantsResponseBody
}

func (o *RotationsGetRotationParticipantsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RotationsGetRotationParticipantsResponse) GetObject() *RotationsGetRotationParticipantsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
