// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/squadcastv1/models/components"
)

type ServicesGetServicesRequest struct {
	OwnerID     *string `queryParam:"style=form,explode=false,name=owner_id"`
	EntityOwner *string `queryParam:"style=form,explode=false,name=entity_owner"`
	Name        *string `queryParam:"style=form,explode=false,name=name"`
}

func (o *ServicesGetServicesRequest) GetOwnerID() *string {
	if o == nil {
		return nil
	}
	return o.OwnerID
}

func (o *ServicesGetServicesRequest) GetEntityOwner() *string {
	if o == nil {
		return nil
	}
	return o.EntityOwner
}

func (o *ServicesGetServicesRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// ServicesGetServicesResponseBody - The request has succeeded.
type ServicesGetServicesResponseBody struct {
	Data []components.V3ServicesServiceResponse `json:"data"`
}

func (o *ServicesGetServicesResponseBody) GetData() []components.V3ServicesServiceResponse {
	if o == nil {
		return []components.V3ServicesServiceResponse{}
	}
	return o.Data
}

type ServicesGetServicesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *ServicesGetServicesResponseBody
}

func (o *ServicesGetServicesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ServicesGetServicesResponse) GetObject() *ServicesGetServicesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
