// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type ServicesGetServicesByNameRequest struct {
	Name    string `queryParam:"style=form,explode=false,name=name"`
	OwnerID string `queryParam:"style=form,explode=false,name=owner_id"`
}

func (o *ServicesGetServicesByNameRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ServicesGetServicesByNameRequest) GetOwnerID() string {
	if o == nil {
		return ""
	}
	return o.OwnerID
}

// ServicesGetServicesByNameResponseBody - The request has succeeded.
type ServicesGetServicesByNameResponseBody struct {
	Data components.V3ServicesServiceResponse `json:"data"`
}

func (o *ServicesGetServicesByNameResponseBody) GetData() components.V3ServicesServiceResponse {
	if o == nil {
		return components.V3ServicesServiceResponse{}
	}
	return o.Data
}

type ServicesGetServicesByNameResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *ServicesGetServicesByNameResponseBody
}

func (o *ServicesGetServicesByNameResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ServicesGetServicesByNameResponse) GetObject() *ServicesGetServicesByNameResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
