// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/squadcastv1/models/components"
)

type ServicesDeleteServiceRequest struct {
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceID"`
}

func (o *ServicesDeleteServiceRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

// ServicesDeleteServiceResponseBody - There is no content to send for this request, but the headers may be useful.
type ServicesDeleteServiceResponseBody struct {
}

type ServicesDeleteServiceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (o *ServicesDeleteServiceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ServicesDeleteServiceResponse) GetBody() []byte {
	if o == nil {
		return nil
	}
	return o.Body
}
