// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/squadcastv1/models/components"
)

// SquadsCreateSquadV4ResponseBody - The request has succeeded and a new resource has been created as a result.
type SquadsCreateSquadV4ResponseBody struct {
	Data components.V4SquadsCreateSquadResponse `json:"data"`
}

func (s *SquadsCreateSquadV4ResponseBody) GetData() components.V4SquadsCreateSquadResponse {
	if s == nil {
		return components.V4SquadsCreateSquadResponse{}
	}
	return s.Data
}

type SquadsCreateSquadV4Response struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded and a new resource has been created as a result.
	Object *SquadsCreateSquadV4ResponseBody
}

func (s *SquadsCreateSquadV4Response) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SquadsCreateSquadV4Response) GetObject() *SquadsCreateSquadV4ResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
