// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type SquadsRemoveSquadMemberRequest struct {
	SquadID     string `pathParam:"style=simple,explode=false,name=squadID"`
	MemberID    string `pathParam:"style=simple,explode=false,name=memberID"`
	ReplaceWith string `queryParam:"style=form,explode=true,name=replaceWith"`
}

func (o *SquadsRemoveSquadMemberRequest) GetSquadID() string {
	if o == nil {
		return ""
	}
	return o.SquadID
}

func (o *SquadsRemoveSquadMemberRequest) GetMemberID() string {
	if o == nil {
		return ""
	}
	return o.MemberID
}

func (o *SquadsRemoveSquadMemberRequest) GetReplaceWith() string {
	if o == nil {
		return ""
	}
	return o.ReplaceWith
}

type SquadsRemoveSquadMemberResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	V4SquadsRemoveSquadMemberResponse *components.V4SquadsRemoveSquadMemberResponse
}

func (o *SquadsRemoveSquadMemberResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SquadsRemoveSquadMemberResponse) GetV4SquadsRemoveSquadMemberResponse() *components.V4SquadsRemoveSquadMemberResponse {
	if o == nil {
		return nil
	}
	return o.V4SquadsRemoveSquadMemberResponse
}
