// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type TeamsAddTeamMemberRequest struct {
	TeamID                      string                                 `pathParam:"style=simple,explode=false,name=teamId"`
	V3TeamsAddTeamMemberRequest components.V3TeamsAddTeamMemberRequest `request:"mediaType=application/json"`
}

func (o *TeamsAddTeamMemberRequest) GetTeamID() string {
	if o == nil {
		return ""
	}
	return o.TeamID
}

func (o *TeamsAddTeamMemberRequest) GetV3TeamsAddTeamMemberRequest() components.V3TeamsAddTeamMemberRequest {
	if o == nil {
		return components.V3TeamsAddTeamMemberRequest{}
	}
	return o.V3TeamsAddTeamMemberRequest
}

// TeamsAddTeamMemberResponseBody - The request has succeeded and a new resource has been created as a result.
type TeamsAddTeamMemberResponseBody struct {
	Data components.V3TeamsTeamMemberResponse `json:"data"`
}

func (o *TeamsAddTeamMemberResponseBody) GetData() components.V3TeamsTeamMemberResponse {
	if o == nil {
		return components.V3TeamsTeamMemberResponse{}
	}
	return o.Data
}

type TeamsAddTeamMemberResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded and a new resource has been created as a result.
	Object *TeamsAddTeamMemberResponseBody
}

func (o *TeamsAddTeamMemberResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *TeamsAddTeamMemberResponse) GetObject() *TeamsAddTeamMemberResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
