// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type WebformsRemoveWebformRequest struct {
	WebformID int64   `pathParam:"style=simple,explode=false,name=webformId"`
	OwnerID   *string `queryParam:"style=form,explode=false,name=owner_id"`
}

func (o *WebformsRemoveWebformRequest) GetWebformID() int64 {
	if o == nil {
		return 0
	}
	return o.WebformID
}

func (o *WebformsRemoveWebformRequest) GetOwnerID() *string {
	if o == nil {
		return nil
	}
	return o.OwnerID
}

// WebformsRemoveWebformResponseBody - The request has succeeded.
type WebformsRemoveWebformResponseBody struct {
	Data string `json:"data"`
}

func (o *WebformsRemoveWebformResponseBody) GetData() string {
	if o == nil {
		return ""
	}
	return o.Data
}

type WebformsRemoveWebformResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *WebformsRemoveWebformResponseBody
}

func (o *WebformsRemoveWebformResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *WebformsRemoveWebformResponse) GetObject() *WebformsRemoveWebformResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
