// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// WebhooksCreateWebhookBody - The body type of the operation request or response.
type WebhooksCreateWebhookBody struct {
	Data components.V3ExtensionsWebhooksWebhookResponse `json:"data"`
}

func (o *WebhooksCreateWebhookBody) GetData() components.V3ExtensionsWebhooksWebhookResponse {
	if o == nil {
		return components.V3ExtensionsWebhooksWebhookResponse{}
	}
	return o.Data
}

// WebhooksCreateWebhookResponseBody - The request has succeeded and a new resource has been created as a result.
type WebhooksCreateWebhookResponseBody struct {
	// The body type of the operation request or response.
	Body WebhooksCreateWebhookBody `json:"body"`
}

func (o *WebhooksCreateWebhookResponseBody) GetBody() WebhooksCreateWebhookBody {
	if o == nil {
		return WebhooksCreateWebhookBody{}
	}
	return o.Body
}

type WebhooksCreateWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded and a new resource has been created as a result.
	Object *WebhooksCreateWebhookResponseBody
}

func (o *WebhooksCreateWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *WebhooksCreateWebhookResponse) GetObject() *WebhooksCreateWebhookResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
