// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Detail struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

func (o *Detail) GetField() string {
	if o == nil {
		return ""
	}
	return o.Field
}

func (o *Detail) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

type Error struct {
	Code    string   `json:"code"`
	Message string   `json:"message"`
	Details []Detail `json:"details,omitempty"`
}

func (o *Error) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *Error) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *Error) GetDetails() []Detail {
	if o == nil {
		return nil
	}
	return o.Details
}
