// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3GlobalEventRulesRuleAction struct {
	// The service ID to which the alert should be routed.
	RouteTo string `json:"route_to"`
}

func (o *V3GlobalEventRulesRuleAction) GetRouteTo() string {
	if o == nil {
		return ""
	}
	return o.RouteTo
}
