// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3GlobalEventRulesCreateRulesetRequest struct {
	AlertSourceShortname string                        `json:"alert_source_shortname"`
	AlertSourceVersion   string                        `json:"alert_source_version"`
	CatchAllAction       *V3GlobalEventRulesRuleAction `json:"catch_all_action,omitempty"`
}

func (o *V3GlobalEventRulesCreateRulesetRequest) GetAlertSourceShortname() string {
	if o == nil {
		return ""
	}
	return o.AlertSourceShortname
}

func (o *V3GlobalEventRulesCreateRulesetRequest) GetAlertSourceVersion() string {
	if o == nil {
		return ""
	}
	return o.AlertSourceVersion
}

func (o *V3GlobalEventRulesCreateRulesetRequest) GetCatchAllAction() *V3GlobalEventRulesRuleAction {
	if o == nil {
		return nil
	}
	return o.CatchAllAction
}
