// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
	"time"
)

// V3IncidentsAssignedTo - Schema for an assigned entity in an incident.
type V3IncidentsAssignedTo struct {
	ID               string    `json:"id"`
	Type             string    `json:"type"`
	TimeOfAssignment time.Time `json:"timeOfAssignment"`
	Reason           string    `json:"reason"`
}

func (v V3IncidentsAssignedTo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3IncidentsAssignedTo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"id", "type", "timeOfAssignment", "reason"}); err != nil {
		return err
	}
	return nil
}

func (o *V3IncidentsAssignedTo) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *V3IncidentsAssignedTo) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *V3IncidentsAssignedTo) GetTimeOfAssignment() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.TimeOfAssignment
}

func (o *V3IncidentsAssignedTo) GetReason() string {
	if o == nil {
		return ""
	}
	return o.Reason
}
