// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ReassignTo struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}

func (o *ReassignTo) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ReassignTo) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

// V3IncidentsReassignIncidentRequest - Request body for reassigning an incident.
type V3IncidentsReassignIncidentRequest struct {
	ReassignTo ReassignTo `json:"reassignTo"`
}

func (o *V3IncidentsReassignIncidentRequest) GetReassignTo() ReassignTo {
	if o == nil {
		return ReassignTo{}
	}
	return o.ReassignTo
}
