// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3IncidentsNotesUpdateNoteRequest - Request body for updating an existing note.
type V3IncidentsNotesUpdateNoteRequest struct {
	Message     string   `json:"message"`
	Attachments []string `json:"attachments"`
}

func (o *V3IncidentsNotesUpdateNoteRequest) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *V3IncidentsNotesUpdateNoteRequest) GetAttachments() []string {
	if o == nil {
		return []string{}
	}
	return o.Attachments
}
