// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type URLObj struct {
	URL    *string `json:"url,omitempty"`
	Method *string `json:"method,omitempty"`
}

func (o *URLObj) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

func (o *URLObj) GetMethod() *string {
	if o == nil {
		return nil
	}
	return o.Method
}

type V3IncidentsIncidentActionsWebhookActionResponseHeader struct {
	ContentType string `json:"Content-Type"`
}

func (o *V3IncidentsIncidentActionsWebhookActionResponseHeader) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

// V3IncidentsIncidentActionsWebhookActionResponse - Represents the response structure for triggering a webhook manually.
type V3IncidentsIncidentActionsWebhookActionResponse struct {
	ID                        string                                                `json:"id"`
	CreatedAt                 string                                                `json:"created_at"`
	UpdatedAt                 string                                                `json:"updated_at"`
	Version                   string                                                `json:"version"`
	OrganizationID            string                                                `json:"organization_id"`
	AuthorID                  string                                                `json:"author_id"`
	Name                      string                                                `json:"name"`
	Slug                      string                                                `json:"slug"`
	Description               string                                                `json:"description"`
	Triggers                  []string                                              `json:"triggers"`
	Urls                      []URLObj                                              `json:"urls"`
	Teams                     []string                                              `json:"teams"`
	IsAllTeamsConfigured      bool                                                  `json:"is_all_teams_configured"`
	CustomPayloadTemplateSlug string                                                `json:"custom_payload_template_slug"`
	Header                    V3IncidentsIncidentActionsWebhookActionResponseHeader `json:"header"`
	Filters                   any                                                   `json:"filters"`
	TriggerType               string                                                `json:"trigger_type"`
	Language                  string                                                `json:"language"`
	MaxRetry                  int64                                                 `json:"max_retry"`
	MailIds                   []string                                              `json:"mail_ids"`
	PayloadType               string                                                `json:"payload_type"`
	CustomPayload             string                                                `json:"custom_payload"`
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetAuthorID() string {
	if o == nil {
		return ""
	}
	return o.AuthorID
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetTriggers() []string {
	if o == nil {
		return []string{}
	}
	return o.Triggers
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetUrls() []URLObj {
	if o == nil {
		return []URLObj{}
	}
	return o.Urls
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetTeams() []string {
	if o == nil {
		return []string{}
	}
	return o.Teams
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetIsAllTeamsConfigured() bool {
	if o == nil {
		return false
	}
	return o.IsAllTeamsConfigured
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetCustomPayloadTemplateSlug() string {
	if o == nil {
		return ""
	}
	return o.CustomPayloadTemplateSlug
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetHeader() V3IncidentsIncidentActionsWebhookActionResponseHeader {
	if o == nil {
		return V3IncidentsIncidentActionsWebhookActionResponseHeader{}
	}
	return o.Header
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetFilters() any {
	if o == nil {
		return nil
	}
	return o.Filters
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetTriggerType() string {
	if o == nil {
		return ""
	}
	return o.TriggerType
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetLanguage() string {
	if o == nil {
		return ""
	}
	return o.Language
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetMaxRetry() int64 {
	if o == nil {
		return 0
	}
	return o.MaxRetry
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetMailIds() []string {
	if o == nil {
		return []string{}
	}
	return o.MailIds
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetPayloadType() string {
	if o == nil {
		return ""
	}
	return o.PayloadType
}

func (o *V3IncidentsIncidentActionsWebhookActionResponse) GetCustomPayload() string {
	if o == nil {
		return ""
	}
	return o.CustomPayload
}
