// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3IncidentsAptaMessageResponse struct {
	Message string `json:"message"`
}

func (o *V3IncidentsAptaMessageResponse) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}
