// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3IncidentsPostmortemsCreatePostmortemRequest - Request body for creating a new postmortem.
type V3IncidentsPostmortemsCreatePostmortemRequest struct {
	OwnerID    string `json:"owner_id"`
	Title      string `json:"title"`
	Postmortem string `json:"postmortem"`
	// Represents the status of a postmortem.
	Status      V3IncidentsPostmortemsPostmortemStatus              `json:"status"`
	FollowUps   []V3IncidentsPostmortemsPostmortemFollowUp          `json:"follow_ups"`
	Attachments []V3IncidentsPostmortemsPostmortemAttachmentRequest `json:"attachments"`
}

func (o *V3IncidentsPostmortemsCreatePostmortemRequest) GetOwnerID() string {
	if o == nil {
		return ""
	}
	return o.OwnerID
}

func (o *V3IncidentsPostmortemsCreatePostmortemRequest) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *V3IncidentsPostmortemsCreatePostmortemRequest) GetPostmortem() string {
	if o == nil {
		return ""
	}
	return o.Postmortem
}

func (o *V3IncidentsPostmortemsCreatePostmortemRequest) GetStatus() V3IncidentsPostmortemsPostmortemStatus {
	if o == nil {
		return V3IncidentsPostmortemsPostmortemStatus("")
	}
	return o.Status
}

func (o *V3IncidentsPostmortemsCreatePostmortemRequest) GetFollowUps() []V3IncidentsPostmortemsPostmortemFollowUp {
	if o == nil {
		return []V3IncidentsPostmortemsPostmortemFollowUp{}
	}
	return o.FollowUps
}

func (o *V3IncidentsPostmortemsCreatePostmortemRequest) GetAttachments() []V3IncidentsPostmortemsPostmortemAttachmentRequest {
	if o == nil {
		return []V3IncidentsPostmortemsPostmortemAttachmentRequest{}
	}
	return o.Attachments
}
