// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3IncidentsCommunicationCardsCommunicationCardResponse - Represents a communication card.
type V3IncidentsCommunicationCardsCommunicationCardResponse struct {
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
	DeletedAt  any    `json:"deleted_at"`
	ID         int64  `json:"id"`
	IncidentID string `json:"incident_id"`
	URL        string `json:"url"`
	Type       string `json:"type"`
	Title      string `json:"title"`
	ChannelID  string `json:"channel_id"`
	ArchivedAt any    `json:"archived_at"`
}

func (o *V3IncidentsCommunicationCardsCommunicationCardResponse) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *V3IncidentsCommunicationCardsCommunicationCardResponse) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}

func (o *V3IncidentsCommunicationCardsCommunicationCardResponse) GetDeletedAt() any {
	if o == nil {
		return nil
	}
	return o.DeletedAt
}

func (o *V3IncidentsCommunicationCardsCommunicationCardResponse) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *V3IncidentsCommunicationCardsCommunicationCardResponse) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

func (o *V3IncidentsCommunicationCardsCommunicationCardResponse) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *V3IncidentsCommunicationCardsCommunicationCardResponse) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *V3IncidentsCommunicationCardsCommunicationCardResponse) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *V3IncidentsCommunicationCardsCommunicationCardResponse) GetChannelID() string {
	if o == nil {
		return ""
	}
	return o.ChannelID
}

func (o *V3IncidentsCommunicationCardsCommunicationCardResponse) GetArchivedAt() any {
	if o == nil {
		return nil
	}
	return o.ArchivedAt
}
