// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3IncidentsIncidentActionsRebuildCircleCIProjectRequest - Request body for rebuilding a project in CircleCI.
type V3IncidentsIncidentActionsRebuildCircleCIProjectRequest struct {
	VcsType  string `json:"vcs_type"`
	Username string `json:"username"`
	Reponame string `json:"reponame"`
}

func (o *V3IncidentsIncidentActionsRebuildCircleCIProjectRequest) GetVcsType() string {
	if o == nil {
		return ""
	}
	return o.VcsType
}

func (o *V3IncidentsIncidentActionsRebuildCircleCIProjectRequest) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

func (o *V3IncidentsIncidentActionsRebuildCircleCIProjectRequest) GetReponame() string {
	if o == nil {
		return ""
	}
	return o.Reponame
}
