// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3IncidentsTagsAnalyticsMetrics - Analytics metrics for TTA (Time to Acknowledge) and TTR (Time to Resolve).
type V3IncidentsTagsAnalyticsMetrics struct {
	Time               int64  `json:"time"`
	UserID             string `json:"userId"`
	EscalationPolicyID string `json:"escalationPolicyId"`
	SquadID            string `json:"squadId"`
}

func (o *V3IncidentsTagsAnalyticsMetrics) GetTime() int64 {
	if o == nil {
		return 0
	}
	return o.Time
}

func (o *V3IncidentsTagsAnalyticsMetrics) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

func (o *V3IncidentsTagsAnalyticsMetrics) GetEscalationPolicyID() string {
	if o == nil {
		return ""
	}
	return o.EscalationPolicyID
}

func (o *V3IncidentsTagsAnalyticsMetrics) GetSquadID() string {
	if o == nil {
		return ""
	}
	return o.SquadID
}
