// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
)

type V3ServicesOverlayDedupKeyOverlay struct {
	Template string `json:"template"`
	Duration int    `json:"duration"`
}

func (v V3ServicesOverlayDedupKeyOverlay) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3ServicesOverlayDedupKeyOverlay) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"template", "duration"}); err != nil {
		return err
	}
	return nil
}

func (o *V3ServicesOverlayDedupKeyOverlay) GetTemplate() string {
	if o == nil {
		return ""
	}
	return o.Template
}

func (o *V3ServicesOverlayDedupKeyOverlay) GetDuration() int {
	if o == nil {
		return 0
	}
	return o.Duration
}
