// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ServicesAPTAConfigRequest struct {
	IsEnabled     bool  `json:"is_enabled"`
	TimeoutInMins int64 `json:"timeout_in_mins"`
}

func (o *V3ServicesAPTAConfigRequest) GetIsEnabled() bool {
	if o == nil {
		return false
	}
	return o.IsEnabled
}

func (o *V3ServicesAPTAConfigRequest) GetTimeoutInMins() int64 {
	if o == nil {
		return 0
	}
	return o.TimeoutInMins
}
