// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
	"time"
)

type V3ServicesOverlayCustomContentOverlayResponseOverlayTemplateType string

const (
	V3ServicesOverlayCustomContentOverlayResponseOverlayTemplateTypeMessage     V3ServicesOverlayCustomContentOverlayResponseOverlayTemplateType = "message"
	V3ServicesOverlayCustomContentOverlayResponseOverlayTemplateTypeDescription V3ServicesOverlayCustomContentOverlayResponseOverlayTemplateType = "description"
)

func (e V3ServicesOverlayCustomContentOverlayResponseOverlayTemplateType) ToPointer() *V3ServicesOverlayCustomContentOverlayResponseOverlayTemplateType {
	return &e
}
func (e *V3ServicesOverlayCustomContentOverlayResponseOverlayTemplateType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "message":
		fallthrough
	case "description":
		*e = V3ServicesOverlayCustomContentOverlayResponseOverlayTemplateType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V3ServicesOverlayCustomContentOverlayResponseOverlayTemplateType: %v", v)
	}
}

type V3ServicesOverlayCustomContentOverlayResponse struct {
	CreatedAt            time.Time                                                        `json:"created_at"`
	UpdatedAt            time.Time                                                        `json:"updated_at"`
	DeletedAt            *time.Time                                                       `json:"deleted_at"`
	OrgID                string                                                           `json:"org_id"`
	ServiceID            string                                                           `json:"service_id"`
	AlertSourceVersion   string                                                           `json:"alert_source_version"`
	AlertSourceShortname string                                                           `json:"alert_source_shortname"`
	OverlayTemplateType  V3ServicesOverlayCustomContentOverlayResponseOverlayTemplateType `json:"overlay_template_type"`
	Overlay              V3ServicesOverlayCustomContent                                   `json:"overlay"`
	CreatedBy            string                                                           `json:"created_by"`
	UpdatedBy            string                                                           `json:"updated_by"`
	AlertSourceType      string                                                           `json:"alert_source_type"`
}

func (v V3ServicesOverlayCustomContentOverlayResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3ServicesOverlayCustomContentOverlayResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"created_at", "updated_at", "deleted_at", "org_id", "service_id", "alert_source_version", "alert_source_shortname", "overlay_template_type", "overlay", "created_by", "updated_by", "alert_source_type"}); err != nil {
		return err
	}
	return nil
}

func (o *V3ServicesOverlayCustomContentOverlayResponse) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *V3ServicesOverlayCustomContentOverlayResponse) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *V3ServicesOverlayCustomContentOverlayResponse) GetDeletedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.DeletedAt
}

func (o *V3ServicesOverlayCustomContentOverlayResponse) GetOrgID() string {
	if o == nil {
		return ""
	}
	return o.OrgID
}

func (o *V3ServicesOverlayCustomContentOverlayResponse) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

func (o *V3ServicesOverlayCustomContentOverlayResponse) GetAlertSourceVersion() string {
	if o == nil {
		return ""
	}
	return o.AlertSourceVersion
}

func (o *V3ServicesOverlayCustomContentOverlayResponse) GetAlertSourceShortname() string {
	if o == nil {
		return ""
	}
	return o.AlertSourceShortname
}

func (o *V3ServicesOverlayCustomContentOverlayResponse) GetOverlayTemplateType() V3ServicesOverlayCustomContentOverlayResponseOverlayTemplateType {
	if o == nil {
		return V3ServicesOverlayCustomContentOverlayResponseOverlayTemplateType("")
	}
	return o.OverlayTemplateType
}

func (o *V3ServicesOverlayCustomContentOverlayResponse) GetOverlay() V3ServicesOverlayCustomContent {
	if o == nil {
		return V3ServicesOverlayCustomContent{}
	}
	return o.Overlay
}

func (o *V3ServicesOverlayCustomContentOverlayResponse) GetCreatedBy() string {
	if o == nil {
		return ""
	}
	return o.CreatedBy
}

func (o *V3ServicesOverlayCustomContentOverlayResponse) GetUpdatedBy() string {
	if o == nil {
		return ""
	}
	return o.UpdatedBy
}

func (o *V3ServicesOverlayCustomContentOverlayResponse) GetAlertSourceType() string {
	if o == nil {
		return ""
	}
	return o.AlertSourceType
}
