// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ServicesJiraProject struct {
	ID   string `json:"id"`
	Key  string `json:"key"`
	Name string `json:"name"`
}

func (o *V3ServicesJiraProject) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *V3ServicesJiraProject) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *V3ServicesJiraProject) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
