// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Insights struct {
	ErrorBudgetConsumptionForPast30days int64 `json:"error_budget_consumption_for_past_30days"`
}

func (o *Insights) GetErrorBudgetConsumptionForPast30days() int64 {
	if o == nil {
		return 0
	}
	return o.ErrorBudgetConsumptionForPast30days
}

type V3SLOSLOWithInsightsResponse struct {
	Insights *Insights `json:"insights,omitempty"`
	Slo      V3SloSlo  `json:"slo"`
}

func (o *V3SLOSLOWithInsightsResponse) GetInsights() *Insights {
	if o == nil {
		return nil
	}
	return o.Insights
}

func (o *V3SLOSLOWithInsightsResponse) GetSlo() V3SloSlo {
	if o == nil {
		return V3SloSlo{}
	}
	return o.Slo
}
