// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3TeamsTeamRoleResponse struct {
	ID        string            `json:"id"`
	Name      string            `json:"name"`
	Slug      string            `json:"slug"`
	Default   bool              `json:"default"`
	Abilities *V3TeamsAbilities `json:"abilities,omitempty"`
}

func (o *V3TeamsTeamRoleResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *V3TeamsTeamRoleResponse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *V3TeamsTeamRoleResponse) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *V3TeamsTeamRoleResponse) GetDefault() bool {
	if o == nil {
		return false
	}
	return o.Default
}

func (o *V3TeamsTeamRoleResponse) GetAbilities() *V3TeamsAbilities {
	if o == nil {
		return nil
	}
	return o.Abilities
}
