// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/SquadcastHub/squadcast-sdk-go/squadcastv1/internal/utils"
)

type V3WorkflowsSqSendEmailName string

const (
	V3WorkflowsSqSendEmailNameSqSendEmail V3WorkflowsSqSendEmailName = "sq_send_email"
)

func (e V3WorkflowsSqSendEmailName) ToPointer() *V3WorkflowsSqSendEmailName {
	return &e
}
func (e *V3WorkflowsSqSendEmailName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "sq_send_email":
		*e = V3WorkflowsSqSendEmailName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V3WorkflowsSqSendEmailName: %v", v)
	}
}

type V3WorkflowsSqSendEmailData struct {
	To      []string `json:"to"`
	Subject string   `json:"subject"`
	Body    string   `json:"body"`
}

func (v V3WorkflowsSqSendEmailData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3WorkflowsSqSendEmailData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"to", "subject", "body"}); err != nil {
		return err
	}
	return nil
}

func (o *V3WorkflowsSqSendEmailData) GetTo() []string {
	if o == nil {
		return []string{}
	}
	return o.To
}

func (o *V3WorkflowsSqSendEmailData) GetSubject() string {
	if o == nil {
		return ""
	}
	return o.Subject
}

func (o *V3WorkflowsSqSendEmailData) GetBody() string {
	if o == nil {
		return ""
	}
	return o.Body
}

type V3WorkflowsSqSendEmail struct {
	Name V3WorkflowsSqSendEmailName `json:"name"`
	Data V3WorkflowsSqSendEmailData `json:"data"`
}

func (v V3WorkflowsSqSendEmail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3WorkflowsSqSendEmail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"name", "data"}); err != nil {
		return err
	}
	return nil
}

func (o *V3WorkflowsSqSendEmail) GetName() V3WorkflowsSqSendEmailName {
	if o == nil {
		return V3WorkflowsSqSendEmailName("")
	}
	return o.Name
}

func (o *V3WorkflowsSqSendEmail) GetData() V3WorkflowsSqSendEmailData {
	if o == nil {
		return V3WorkflowsSqSendEmailData{}
	}
	return o.Data
}
