// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/SquadcastHub/squadcast-sdk-go/squadcastv1/internal/utils"
)

type V3WorkflowsMsTeamsMessageUserName string

const (
	V3WorkflowsMsTeamsMessageUserNameMsteamsMessageUser V3WorkflowsMsTeamsMessageUserName = "msteams_message_user"
)

func (e V3WorkflowsMsTeamsMessageUserName) ToPointer() *V3WorkflowsMsTeamsMessageUserName {
	return &e
}
func (e *V3WorkflowsMsTeamsMessageUserName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "msteams_message_user":
		*e = V3WorkflowsMsTeamsMessageUserName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V3WorkflowsMsTeamsMessageUserName: %v", v)
	}
}

type V3WorkflowsMsTeamsMessageUserData struct {
	MemberID string `json:"member_id"`
	Message  string `json:"message"`
}

func (v V3WorkflowsMsTeamsMessageUserData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3WorkflowsMsTeamsMessageUserData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"member_id", "message"}); err != nil {
		return err
	}
	return nil
}

func (o *V3WorkflowsMsTeamsMessageUserData) GetMemberID() string {
	if o == nil {
		return ""
	}
	return o.MemberID
}

func (o *V3WorkflowsMsTeamsMessageUserData) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

type V3WorkflowsMsTeamsMessageUser struct {
	Name V3WorkflowsMsTeamsMessageUserName `json:"name"`
	Data V3WorkflowsMsTeamsMessageUserData `json:"data"`
}

func (v V3WorkflowsMsTeamsMessageUser) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3WorkflowsMsTeamsMessageUser) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"name", "data"}); err != nil {
		return err
	}
	return nil
}

func (o *V3WorkflowsMsTeamsMessageUser) GetName() V3WorkflowsMsTeamsMessageUserName {
	if o == nil {
		return V3WorkflowsMsTeamsMessageUserName("")
	}
	return o.Name
}

func (o *V3WorkflowsMsTeamsMessageUser) GetData() V3WorkflowsMsTeamsMessageUserData {
	if o == nil {
		return V3WorkflowsMsTeamsMessageUserData{}
	}
	return o.Data
}
