// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type V3WorkflowsCreateWorkflowRequestOwnerType string

const (
	V3WorkflowsCreateWorkflowRequestOwnerTypeUser  V3WorkflowsCreateWorkflowRequestOwnerType = "user"
	V3WorkflowsCreateWorkflowRequestOwnerTypeSquad V3WorkflowsCreateWorkflowRequestOwnerType = "squad"
)

func (e V3WorkflowsCreateWorkflowRequestOwnerType) ToPointer() *V3WorkflowsCreateWorkflowRequestOwnerType {
	return &e
}
func (e *V3WorkflowsCreateWorkflowRequestOwnerType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "user":
		fallthrough
	case "squad":
		*e = V3WorkflowsCreateWorkflowRequestOwnerType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V3WorkflowsCreateWorkflowRequestOwnerType: %v", v)
	}
}

type V3WorkflowsCreateWorkflowRequest struct {
	Title       string                                     `json:"title"`
	Description *string                                    `json:"description,omitempty"`
	OwnerID     string                                     `json:"owner_id"`
	OwnerType   *V3WorkflowsCreateWorkflowRequestOwnerType `json:"owner_type,omitempty"`
	EntityOwner *V3WorkflowsEntityOwner                    `json:"entity_owner,omitempty"`
	Tags        []V3WorkflowsTag                           `json:"tags,omitempty"`
	Trigger     V3WorkflowsWorkflowTrigger                 `json:"trigger"`
	Filters     V3WorkflowsCreateWorkflowFilter            `json:"filters"`
	Actions     []V3WorkflowsActionRequest                 `json:"actions"`
	Enabled     *bool                                      `json:"enabled,omitempty"`
}

func (o *V3WorkflowsCreateWorkflowRequest) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *V3WorkflowsCreateWorkflowRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *V3WorkflowsCreateWorkflowRequest) GetOwnerID() string {
	if o == nil {
		return ""
	}
	return o.OwnerID
}

func (o *V3WorkflowsCreateWorkflowRequest) GetOwnerType() *V3WorkflowsCreateWorkflowRequestOwnerType {
	if o == nil {
		return nil
	}
	return o.OwnerType
}

func (o *V3WorkflowsCreateWorkflowRequest) GetEntityOwner() *V3WorkflowsEntityOwner {
	if o == nil {
		return nil
	}
	return o.EntityOwner
}

func (o *V3WorkflowsCreateWorkflowRequest) GetTags() []V3WorkflowsTag {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *V3WorkflowsCreateWorkflowRequest) GetTrigger() V3WorkflowsWorkflowTrigger {
	if o == nil {
		return V3WorkflowsWorkflowTrigger("")
	}
	return o.Trigger
}

func (o *V3WorkflowsCreateWorkflowRequest) GetFilters() V3WorkflowsCreateWorkflowFilter {
	if o == nil {
		return V3WorkflowsCreateWorkflowFilter{}
	}
	return o.Filters
}

func (o *V3WorkflowsCreateWorkflowRequest) GetActions() []V3WorkflowsActionRequest {
	if o == nil {
		return []V3WorkflowsActionRequest{}
	}
	return o.Actions
}

func (o *V3WorkflowsCreateWorkflowRequest) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}
