// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4Participant struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}

func (o *V4Participant) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *V4Participant) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}
