// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4ParticipantGroup struct {
	Participants []V4Participant `json:"participants"`
}

func (o *V4ParticipantGroup) GetParticipants() []V4Participant {
	if o == nil {
		return []V4Participant{}
	}
	return o.Participants
}
