// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4ShiftTimeSlot struct {
	StartHour int64   `json:"startHour"`
	StartMin  int64   `json:"startMin"`
	Duration  int64   `json:"duration"`
	DayOfWeek *string `json:"dayOfWeek,omitempty"`
}

func (o *V4ShiftTimeSlot) GetStartHour() int64 {
	if o == nil {
		return 0
	}
	return o.StartHour
}

func (o *V4ShiftTimeSlot) GetStartMin() int64 {
	if o == nil {
		return 0
	}
	return o.StartMin
}

func (o *V4ShiftTimeSlot) GetDuration() int64 {
	if o == nil {
		return 0
	}
	return o.Duration
}

func (o *V4ShiftTimeSlot) GetDayOfWeek() *string {
	if o == nil {
		return nil
	}
	return o.DayOfWeek
}
