// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4StatusPagesIssuesCreateIssueResponse struct {
	ID           int64   `json:"id"`
	ComponentIDs []int64 `json:"componentIDs"`
	Title        string  `json:"title"`
}

func (o *V4StatusPagesIssuesCreateIssueResponse) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *V4StatusPagesIssuesCreateIssueResponse) GetComponentIDs() []int64 {
	if o == nil {
		return []int64{}
	}
	return o.ComponentIDs
}

func (o *V4StatusPagesIssuesCreateIssueResponse) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}
