// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4StatusPagesComponentsGetComponentByIDResponse struct {
	ID               int64  `json:"id"`
	PageID           int64  `json:"pageID"`
	Name             string `json:"name"`
	Description      string `json:"description"`
	StatusID         *int64 `json:"statusID,omitempty"`
	UnderMaintenance bool   `json:"underMaintenance"`
}

func (o *V4StatusPagesComponentsGetComponentByIDResponse) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *V4StatusPagesComponentsGetComponentByIDResponse) GetPageID() int64 {
	if o == nil {
		return 0
	}
	return o.PageID
}

func (o *V4StatusPagesComponentsGetComponentByIDResponse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *V4StatusPagesComponentsGetComponentByIDResponse) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *V4StatusPagesComponentsGetComponentByIDResponse) GetStatusID() *int64 {
	if o == nil {
		return nil
	}
	return o.StatusID
}

func (o *V4StatusPagesComponentsGetComponentByIDResponse) GetUnderMaintenance() bool {
	if o == nil {
		return false
	}
	return o.UnderMaintenance
}
