// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4StatusPagesComponentsUpdateComponentByIDResponse struct {
	ID                int64  `json:"id"`
	PageID            int64  `json:"pageID"`
	Name              string `json:"name"`
	Description       string `json:"description"`
	GroupID           *int64 `json:"groupID,omitempty"`
	AllowSubscription bool   `json:"allowSubscription"`
}

func (o *V4StatusPagesComponentsUpdateComponentByIDResponse) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *V4StatusPagesComponentsUpdateComponentByIDResponse) GetPageID() int64 {
	if o == nil {
		return 0
	}
	return o.PageID
}

func (o *V4StatusPagesComponentsUpdateComponentByIDResponse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *V4StatusPagesComponentsUpdateComponentByIDResponse) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *V4StatusPagesComponentsUpdateComponentByIDResponse) GetGroupID() *int64 {
	if o == nil {
		return nil
	}
	return o.GroupID
}

func (o *V4StatusPagesComponentsUpdateComponentByIDResponse) GetAllowSubscription() bool {
	if o == nil {
		return false
	}
	return o.AllowSubscription
}
