// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/v1/models/components"
)

type StatusPagesListStatusPagesRequest struct {
	PageSize        string `queryParam:"style=form,explode=false,name=pageSize"`
	PageNumber      string `queryParam:"style=form,explode=false,name=pageNumber"`
	FiltersIsPublic string `queryParam:"style=form,explode=false,name=filters.isPublic"`
	TeamID          string `queryParam:"style=form,explode=false,name=teamID"`
}

func (s *StatusPagesListStatusPagesRequest) GetPageSize() string {
	if s == nil {
		return ""
	}
	return s.PageSize
}

func (s *StatusPagesListStatusPagesRequest) GetPageNumber() string {
	if s == nil {
		return ""
	}
	return s.PageNumber
}

func (s *StatusPagesListStatusPagesRequest) GetFiltersIsPublic() string {
	if s == nil {
		return ""
	}
	return s.FiltersIsPublic
}

func (s *StatusPagesListStatusPagesRequest) GetTeamID() string {
	if s == nil {
		return ""
	}
	return s.TeamID
}

type StatusPagesListStatusPagesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	V4StatusPagesListStatusPagesResponse *components.V4StatusPagesListStatusPagesResponse
}

func (s *StatusPagesListStatusPagesResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StatusPagesListStatusPagesResponse) GetV4StatusPagesListStatusPagesResponse() *components.V4StatusPagesListStatusPagesResponse {
	if s == nil {
		return nil
	}
	return s.V4StatusPagesListStatusPagesResponse
}
