// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// IncidentsIncidentPriorityUpdateGatewayTimeoutError - Server error
type IncidentsIncidentPriorityUpdateGatewayTimeoutError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &IncidentsIncidentPriorityUpdateGatewayTimeoutError{}

func (e *IncidentsIncidentPriorityUpdateGatewayTimeoutError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// IncidentsIncidentPriorityUpdateServiceUnavailableError - Service unavailable.
type IncidentsIncidentPriorityUpdateServiceUnavailableError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &IncidentsIncidentPriorityUpdateServiceUnavailableError{}

func (e *IncidentsIncidentPriorityUpdateServiceUnavailableError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// IncidentsIncidentPriorityUpdateBadGatewayError - Server error
type IncidentsIncidentPriorityUpdateBadGatewayError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &IncidentsIncidentPriorityUpdateBadGatewayError{}

func (e *IncidentsIncidentPriorityUpdateBadGatewayError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// IncidentsIncidentPriorityUpdateInternalServerError - Server error
type IncidentsIncidentPriorityUpdateInternalServerError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &IncidentsIncidentPriorityUpdateInternalServerError{}

func (e *IncidentsIncidentPriorityUpdateInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// IncidentsIncidentPriorityUpdateUnprocessableEntityError - Client error
type IncidentsIncidentPriorityUpdateUnprocessableEntityError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &IncidentsIncidentPriorityUpdateUnprocessableEntityError{}

func (e *IncidentsIncidentPriorityUpdateUnprocessableEntityError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// IncidentsIncidentPriorityUpdateConflictError - The request conflicts with the current state of the server.
type IncidentsIncidentPriorityUpdateConflictError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &IncidentsIncidentPriorityUpdateConflictError{}

func (e *IncidentsIncidentPriorityUpdateConflictError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// IncidentsIncidentPriorityUpdateNotFoundError - The server cannot find the requested resource.
type IncidentsIncidentPriorityUpdateNotFoundError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &IncidentsIncidentPriorityUpdateNotFoundError{}

func (e *IncidentsIncidentPriorityUpdateNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// IncidentsIncidentPriorityUpdateForbiddenError - Access is forbidden.
type IncidentsIncidentPriorityUpdateForbiddenError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &IncidentsIncidentPriorityUpdateForbiddenError{}

func (e *IncidentsIncidentPriorityUpdateForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// IncidentsIncidentPriorityUpdatePaymentRequiredError - Client error
type IncidentsIncidentPriorityUpdatePaymentRequiredError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &IncidentsIncidentPriorityUpdatePaymentRequiredError{}

func (e *IncidentsIncidentPriorityUpdatePaymentRequiredError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// IncidentsIncidentPriorityUpdateUnauthorizedError - Access is unauthorized.
type IncidentsIncidentPriorityUpdateUnauthorizedError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &IncidentsIncidentPriorityUpdateUnauthorizedError{}

func (e *IncidentsIncidentPriorityUpdateUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// IncidentsIncidentPriorityUpdateBadRequestError - The server could not understand the request due to invalid syntax.
type IncidentsIncidentPriorityUpdateBadRequestError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &IncidentsIncidentPriorityUpdateBadRequestError{}

func (e *IncidentsIncidentPriorityUpdateBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
