// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// NotesCreateNotesGatewayTimeoutError - Server error
type NotesCreateNotesGatewayTimeoutError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &NotesCreateNotesGatewayTimeoutError{}

func (e *NotesCreateNotesGatewayTimeoutError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// NotesCreateNotesServiceUnavailableError - Service unavailable.
type NotesCreateNotesServiceUnavailableError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &NotesCreateNotesServiceUnavailableError{}

func (e *NotesCreateNotesServiceUnavailableError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// NotesCreateNotesBadGatewayError - Server error
type NotesCreateNotesBadGatewayError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &NotesCreateNotesBadGatewayError{}

func (e *NotesCreateNotesBadGatewayError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// NotesCreateNotesInternalServerError - Server error
type NotesCreateNotesInternalServerError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &NotesCreateNotesInternalServerError{}

func (e *NotesCreateNotesInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// NotesCreateNotesUnprocessableEntityError - Client error
type NotesCreateNotesUnprocessableEntityError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &NotesCreateNotesUnprocessableEntityError{}

func (e *NotesCreateNotesUnprocessableEntityError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// NotesCreateNotesConflictError - The request conflicts with the current state of the server.
type NotesCreateNotesConflictError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &NotesCreateNotesConflictError{}

func (e *NotesCreateNotesConflictError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// NotesCreateNotesNotFoundError - The server cannot find the requested resource.
type NotesCreateNotesNotFoundError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &NotesCreateNotesNotFoundError{}

func (e *NotesCreateNotesNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// NotesCreateNotesForbiddenError - Access is forbidden.
type NotesCreateNotesForbiddenError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &NotesCreateNotesForbiddenError{}

func (e *NotesCreateNotesForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// NotesCreateNotesPaymentRequiredError - Client error
type NotesCreateNotesPaymentRequiredError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &NotesCreateNotesPaymentRequiredError{}

func (e *NotesCreateNotesPaymentRequiredError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// NotesCreateNotesUnauthorizedError - Access is unauthorized.
type NotesCreateNotesUnauthorizedError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &NotesCreateNotesUnauthorizedError{}

func (e *NotesCreateNotesUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// NotesCreateNotesBadRequestError - The server could not understand the request due to invalid syntax.
type NotesCreateNotesBadRequestError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &NotesCreateNotesBadRequestError{}

func (e *NotesCreateNotesBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
