// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// StatusPagesCreateStatusPageGatewayTimeoutError - Server error
type StatusPagesCreateStatusPageGatewayTimeoutError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesCreateStatusPageGatewayTimeoutError{}

func (e *StatusPagesCreateStatusPageGatewayTimeoutError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesCreateStatusPageServiceUnavailableError - Service unavailable.
type StatusPagesCreateStatusPageServiceUnavailableError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesCreateStatusPageServiceUnavailableError{}

func (e *StatusPagesCreateStatusPageServiceUnavailableError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesCreateStatusPageBadGatewayError - Server error
type StatusPagesCreateStatusPageBadGatewayError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesCreateStatusPageBadGatewayError{}

func (e *StatusPagesCreateStatusPageBadGatewayError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesCreateStatusPageInternalServerError - Server error
type StatusPagesCreateStatusPageInternalServerError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesCreateStatusPageInternalServerError{}

func (e *StatusPagesCreateStatusPageInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesCreateStatusPageUnprocessableEntityError - Client error
type StatusPagesCreateStatusPageUnprocessableEntityError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesCreateStatusPageUnprocessableEntityError{}

func (e *StatusPagesCreateStatusPageUnprocessableEntityError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesCreateStatusPageConflictError - The request conflicts with the current state of the server.
type StatusPagesCreateStatusPageConflictError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesCreateStatusPageConflictError{}

func (e *StatusPagesCreateStatusPageConflictError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesCreateStatusPageNotFoundError - The server cannot find the requested resource.
type StatusPagesCreateStatusPageNotFoundError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesCreateStatusPageNotFoundError{}

func (e *StatusPagesCreateStatusPageNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesCreateStatusPageForbiddenError - Access is forbidden.
type StatusPagesCreateStatusPageForbiddenError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesCreateStatusPageForbiddenError{}

func (e *StatusPagesCreateStatusPageForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesCreateStatusPagePaymentRequiredError - Client error
type StatusPagesCreateStatusPagePaymentRequiredError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesCreateStatusPagePaymentRequiredError{}

func (e *StatusPagesCreateStatusPagePaymentRequiredError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesCreateStatusPageUnauthorizedError - Access is unauthorized.
type StatusPagesCreateStatusPageUnauthorizedError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesCreateStatusPageUnauthorizedError{}

func (e *StatusPagesCreateStatusPageUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesCreateStatusPageBadRequestError - The server could not understand the request due to invalid syntax.
type StatusPagesCreateStatusPageBadRequestError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesCreateStatusPageBadRequestError{}

func (e *StatusPagesCreateStatusPageBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
