// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/SquadcastHub/squadcast-sdk-go/squadcastv1/models/components"
)

// StatusPagesListStatusPagesGatewayTimeoutError - Server error
type StatusPagesListStatusPagesGatewayTimeoutError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesListStatusPagesGatewayTimeoutError{}

func (e *StatusPagesListStatusPagesGatewayTimeoutError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesListStatusPagesServiceUnavailableError - Service unavailable.
type StatusPagesListStatusPagesServiceUnavailableError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesListStatusPagesServiceUnavailableError{}

func (e *StatusPagesListStatusPagesServiceUnavailableError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesListStatusPagesBadGatewayError - Server error
type StatusPagesListStatusPagesBadGatewayError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesListStatusPagesBadGatewayError{}

func (e *StatusPagesListStatusPagesBadGatewayError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesListStatusPagesInternalServerError - Server error
type StatusPagesListStatusPagesInternalServerError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesListStatusPagesInternalServerError{}

func (e *StatusPagesListStatusPagesInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesListStatusPagesUnprocessableEntityError - Client error
type StatusPagesListStatusPagesUnprocessableEntityError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesListStatusPagesUnprocessableEntityError{}

func (e *StatusPagesListStatusPagesUnprocessableEntityError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesListStatusPagesConflictError - The request conflicts with the current state of the server.
type StatusPagesListStatusPagesConflictError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesListStatusPagesConflictError{}

func (e *StatusPagesListStatusPagesConflictError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesListStatusPagesNotFoundError - The server cannot find the requested resource.
type StatusPagesListStatusPagesNotFoundError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesListStatusPagesNotFoundError{}

func (e *StatusPagesListStatusPagesNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesListStatusPagesForbiddenError - Access is forbidden.
type StatusPagesListStatusPagesForbiddenError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesListStatusPagesForbiddenError{}

func (e *StatusPagesListStatusPagesForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesListStatusPagesPaymentRequiredError - Client error
type StatusPagesListStatusPagesPaymentRequiredError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesListStatusPagesPaymentRequiredError{}

func (e *StatusPagesListStatusPagesPaymentRequiredError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesListStatusPagesUnauthorizedError - Access is unauthorized.
type StatusPagesListStatusPagesUnauthorizedError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesListStatusPagesUnauthorizedError{}

func (e *StatusPagesListStatusPagesUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// StatusPagesListStatusPagesBadRequestError - The server could not understand the request due to invalid syntax.
type StatusPagesListStatusPagesBadRequestError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &StatusPagesListStatusPagesBadRequestError{}

func (e *StatusPagesListStatusPagesBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
