// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// TeamsCreateTeamGatewayTimeoutError - Server error
type TeamsCreateTeamGatewayTimeoutError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsCreateTeamGatewayTimeoutError{}

func (e *TeamsCreateTeamGatewayTimeoutError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsCreateTeamServiceUnavailableError - Service unavailable.
type TeamsCreateTeamServiceUnavailableError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsCreateTeamServiceUnavailableError{}

func (e *TeamsCreateTeamServiceUnavailableError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsCreateTeamBadGatewayError - Server error
type TeamsCreateTeamBadGatewayError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsCreateTeamBadGatewayError{}

func (e *TeamsCreateTeamBadGatewayError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsCreateTeamInternalServerError - Server error
type TeamsCreateTeamInternalServerError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsCreateTeamInternalServerError{}

func (e *TeamsCreateTeamInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsCreateTeamUnprocessableEntityError - Client error
type TeamsCreateTeamUnprocessableEntityError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsCreateTeamUnprocessableEntityError{}

func (e *TeamsCreateTeamUnprocessableEntityError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsCreateTeamConflictError - The request conflicts with the current state of the server.
type TeamsCreateTeamConflictError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsCreateTeamConflictError{}

func (e *TeamsCreateTeamConflictError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsCreateTeamNotFoundError - The server cannot find the requested resource.
type TeamsCreateTeamNotFoundError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsCreateTeamNotFoundError{}

func (e *TeamsCreateTeamNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsCreateTeamForbiddenError - Access is forbidden.
type TeamsCreateTeamForbiddenError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsCreateTeamForbiddenError{}

func (e *TeamsCreateTeamForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsCreateTeamPaymentRequiredError - Client error
type TeamsCreateTeamPaymentRequiredError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsCreateTeamPaymentRequiredError{}

func (e *TeamsCreateTeamPaymentRequiredError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsCreateTeamUnauthorizedError - Access is unauthorized.
type TeamsCreateTeamUnauthorizedError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsCreateTeamUnauthorizedError{}

func (e *TeamsCreateTeamUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsCreateTeamBadRequestError - The server could not understand the request due to invalid syntax.
type TeamsCreateTeamBadRequestError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsCreateTeamBadRequestError{}

func (e *TeamsCreateTeamBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
