// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/SquadcastHub/squadcast-sdk-go/squadcastv1/models/components"
)

// TeamsGetAllTeamMembersGatewayTimeoutError - Server error
type TeamsGetAllTeamMembersGatewayTimeoutError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsGetAllTeamMembersGatewayTimeoutError{}

func (e *TeamsGetAllTeamMembersGatewayTimeoutError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsGetAllTeamMembersServiceUnavailableError - Service unavailable.
type TeamsGetAllTeamMembersServiceUnavailableError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsGetAllTeamMembersServiceUnavailableError{}

func (e *TeamsGetAllTeamMembersServiceUnavailableError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsGetAllTeamMembersBadGatewayError - Server error
type TeamsGetAllTeamMembersBadGatewayError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsGetAllTeamMembersBadGatewayError{}

func (e *TeamsGetAllTeamMembersBadGatewayError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsGetAllTeamMembersInternalServerError - Server error
type TeamsGetAllTeamMembersInternalServerError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsGetAllTeamMembersInternalServerError{}

func (e *TeamsGetAllTeamMembersInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsGetAllTeamMembersUnprocessableEntityError - Client error
type TeamsGetAllTeamMembersUnprocessableEntityError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsGetAllTeamMembersUnprocessableEntityError{}

func (e *TeamsGetAllTeamMembersUnprocessableEntityError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsGetAllTeamMembersConflictError - The request conflicts with the current state of the server.
type TeamsGetAllTeamMembersConflictError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsGetAllTeamMembersConflictError{}

func (e *TeamsGetAllTeamMembersConflictError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsGetAllTeamMembersNotFoundError - The server cannot find the requested resource.
type TeamsGetAllTeamMembersNotFoundError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsGetAllTeamMembersNotFoundError{}

func (e *TeamsGetAllTeamMembersNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsGetAllTeamMembersForbiddenError - Access is forbidden.
type TeamsGetAllTeamMembersForbiddenError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsGetAllTeamMembersForbiddenError{}

func (e *TeamsGetAllTeamMembersForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsGetAllTeamMembersPaymentRequiredError - Client error
type TeamsGetAllTeamMembersPaymentRequiredError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsGetAllTeamMembersPaymentRequiredError{}

func (e *TeamsGetAllTeamMembersPaymentRequiredError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsGetAllTeamMembersUnauthorizedError - Access is unauthorized.
type TeamsGetAllTeamMembersUnauthorizedError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsGetAllTeamMembersUnauthorizedError{}

func (e *TeamsGetAllTeamMembersUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// TeamsGetAllTeamMembersBadRequestError - The server could not understand the request due to invalid syntax.
type TeamsGetAllTeamMembersBadRequestError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &TeamsGetAllTeamMembersBadRequestError{}

func (e *TeamsGetAllTeamMembersBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
