// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// UsersRemoveTokenGatewayTimeoutError - Server error
type UsersRemoveTokenGatewayTimeoutError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &UsersRemoveTokenGatewayTimeoutError{}

func (e *UsersRemoveTokenGatewayTimeoutError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UsersRemoveTokenServiceUnavailableError - Service unavailable.
type UsersRemoveTokenServiceUnavailableError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &UsersRemoveTokenServiceUnavailableError{}

func (e *UsersRemoveTokenServiceUnavailableError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UsersRemoveTokenBadGatewayError - Server error
type UsersRemoveTokenBadGatewayError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &UsersRemoveTokenBadGatewayError{}

func (e *UsersRemoveTokenBadGatewayError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UsersRemoveTokenInternalServerError - Server error
type UsersRemoveTokenInternalServerError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &UsersRemoveTokenInternalServerError{}

func (e *UsersRemoveTokenInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UsersRemoveTokenUnprocessableEntityError - Client error
type UsersRemoveTokenUnprocessableEntityError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &UsersRemoveTokenUnprocessableEntityError{}

func (e *UsersRemoveTokenUnprocessableEntityError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UsersRemoveTokenConflictError - The request conflicts with the current state of the server.
type UsersRemoveTokenConflictError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &UsersRemoveTokenConflictError{}

func (e *UsersRemoveTokenConflictError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UsersRemoveTokenNotFoundError - The server cannot find the requested resource.
type UsersRemoveTokenNotFoundError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &UsersRemoveTokenNotFoundError{}

func (e *UsersRemoveTokenNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UsersRemoveTokenForbiddenError - Access is forbidden.
type UsersRemoveTokenForbiddenError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &UsersRemoveTokenForbiddenError{}

func (e *UsersRemoveTokenForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UsersRemoveTokenPaymentRequiredError - Client error
type UsersRemoveTokenPaymentRequiredError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &UsersRemoveTokenPaymentRequiredError{}

func (e *UsersRemoveTokenPaymentRequiredError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UsersRemoveTokenUnauthorizedError - Access is unauthorized.
type UsersRemoveTokenUnauthorizedError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &UsersRemoveTokenUnauthorizedError{}

func (e *UsersRemoveTokenUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UsersRemoveTokenBadRequestError - The server could not understand the request due to invalid syntax.
type UsersRemoveTokenBadRequestError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &UsersRemoveTokenBadRequestError{}

func (e *UsersRemoveTokenBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
