// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// WebhooksGetAllWebhooksGatewayTimeoutError - Server error
type WebhooksGetAllWebhooksGatewayTimeoutError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksGetAllWebhooksGatewayTimeoutError{}

func (e *WebhooksGetAllWebhooksGatewayTimeoutError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksGetAllWebhooksServiceUnavailableError - Service unavailable.
type WebhooksGetAllWebhooksServiceUnavailableError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksGetAllWebhooksServiceUnavailableError{}

func (e *WebhooksGetAllWebhooksServiceUnavailableError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksGetAllWebhooksBadGatewayError - Server error
type WebhooksGetAllWebhooksBadGatewayError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksGetAllWebhooksBadGatewayError{}

func (e *WebhooksGetAllWebhooksBadGatewayError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksGetAllWebhooksInternalServerError - Server error
type WebhooksGetAllWebhooksInternalServerError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksGetAllWebhooksInternalServerError{}

func (e *WebhooksGetAllWebhooksInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksGetAllWebhooksUnprocessableEntityError - Client error
type WebhooksGetAllWebhooksUnprocessableEntityError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksGetAllWebhooksUnprocessableEntityError{}

func (e *WebhooksGetAllWebhooksUnprocessableEntityError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksGetAllWebhooksConflictError - The request conflicts with the current state of the server.
type WebhooksGetAllWebhooksConflictError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksGetAllWebhooksConflictError{}

func (e *WebhooksGetAllWebhooksConflictError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksGetAllWebhooksNotFoundError - The server cannot find the requested resource.
type WebhooksGetAllWebhooksNotFoundError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksGetAllWebhooksNotFoundError{}

func (e *WebhooksGetAllWebhooksNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksGetAllWebhooksForbiddenError - Access is forbidden.
type WebhooksGetAllWebhooksForbiddenError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksGetAllWebhooksForbiddenError{}

func (e *WebhooksGetAllWebhooksForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksGetAllWebhooksPaymentRequiredError - Client error
type WebhooksGetAllWebhooksPaymentRequiredError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksGetAllWebhooksPaymentRequiredError{}

func (e *WebhooksGetAllWebhooksPaymentRequiredError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksGetAllWebhooksUnauthorizedError - Access is unauthorized.
type WebhooksGetAllWebhooksUnauthorizedError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksGetAllWebhooksUnauthorizedError{}

func (e *WebhooksGetAllWebhooksUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksGetAllWebhooksBadRequestError - The server could not understand the request due to invalid syntax.
type WebhooksGetAllWebhooksBadRequestError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksGetAllWebhooksBadRequestError{}

func (e *WebhooksGetAllWebhooksBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
