// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/SquadcastHub/squadcast-sdk-go/squadcastv1/models/components"
)

// WebhooksDeleteWebhookGatewayTimeoutError - Server error
type WebhooksDeleteWebhookGatewayTimeoutError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksDeleteWebhookGatewayTimeoutError{}

func (e *WebhooksDeleteWebhookGatewayTimeoutError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksDeleteWebhookServiceUnavailableError - Service unavailable.
type WebhooksDeleteWebhookServiceUnavailableError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksDeleteWebhookServiceUnavailableError{}

func (e *WebhooksDeleteWebhookServiceUnavailableError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksDeleteWebhookBadGatewayError - Server error
type WebhooksDeleteWebhookBadGatewayError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksDeleteWebhookBadGatewayError{}

func (e *WebhooksDeleteWebhookBadGatewayError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksDeleteWebhookInternalServerError - Server error
type WebhooksDeleteWebhookInternalServerError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksDeleteWebhookInternalServerError{}

func (e *WebhooksDeleteWebhookInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksDeleteWebhookUnprocessableEntityError - Client error
type WebhooksDeleteWebhookUnprocessableEntityError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksDeleteWebhookUnprocessableEntityError{}

func (e *WebhooksDeleteWebhookUnprocessableEntityError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksDeleteWebhookConflictError - The request conflicts with the current state of the server.
type WebhooksDeleteWebhookConflictError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksDeleteWebhookConflictError{}

func (e *WebhooksDeleteWebhookConflictError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksDeleteWebhookNotFoundError - The server cannot find the requested resource.
type WebhooksDeleteWebhookNotFoundError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksDeleteWebhookNotFoundError{}

func (e *WebhooksDeleteWebhookNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksDeleteWebhookForbiddenError - Access is forbidden.
type WebhooksDeleteWebhookForbiddenError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksDeleteWebhookForbiddenError{}

func (e *WebhooksDeleteWebhookForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksDeleteWebhookPaymentRequiredError - Client error
type WebhooksDeleteWebhookPaymentRequiredError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksDeleteWebhookPaymentRequiredError{}

func (e *WebhooksDeleteWebhookPaymentRequiredError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksDeleteWebhookUnauthorizedError - Access is unauthorized.
type WebhooksDeleteWebhookUnauthorizedError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksDeleteWebhookUnauthorizedError{}

func (e *WebhooksDeleteWebhookUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WebhooksDeleteWebhookBadRequestError - The server could not understand the request due to invalid syntax.
type WebhooksDeleteWebhookBadRequestError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WebhooksDeleteWebhookBadRequestError{}

func (e *WebhooksDeleteWebhookBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
