// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/SquadcastHub/squadcast-sdk-go/squadcastv1/models/components"
)

// WorkflowsEnabledisableWorkflowGatewayTimeoutError - Server error
type WorkflowsEnabledisableWorkflowGatewayTimeoutError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsEnabledisableWorkflowGatewayTimeoutError{}

func (e *WorkflowsEnabledisableWorkflowGatewayTimeoutError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsEnabledisableWorkflowServiceUnavailableError - Service unavailable.
type WorkflowsEnabledisableWorkflowServiceUnavailableError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsEnabledisableWorkflowServiceUnavailableError{}

func (e *WorkflowsEnabledisableWorkflowServiceUnavailableError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsEnabledisableWorkflowBadGatewayError - Server error
type WorkflowsEnabledisableWorkflowBadGatewayError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsEnabledisableWorkflowBadGatewayError{}

func (e *WorkflowsEnabledisableWorkflowBadGatewayError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsEnabledisableWorkflowInternalServerError - Server error
type WorkflowsEnabledisableWorkflowInternalServerError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsEnabledisableWorkflowInternalServerError{}

func (e *WorkflowsEnabledisableWorkflowInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsEnabledisableWorkflowUnprocessableEntityError - Client error
type WorkflowsEnabledisableWorkflowUnprocessableEntityError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsEnabledisableWorkflowUnprocessableEntityError{}

func (e *WorkflowsEnabledisableWorkflowUnprocessableEntityError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsEnabledisableWorkflowConflictError - The request conflicts with the current state of the server.
type WorkflowsEnabledisableWorkflowConflictError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsEnabledisableWorkflowConflictError{}

func (e *WorkflowsEnabledisableWorkflowConflictError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsEnabledisableWorkflowNotFoundError - The server cannot find the requested resource.
type WorkflowsEnabledisableWorkflowNotFoundError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsEnabledisableWorkflowNotFoundError{}

func (e *WorkflowsEnabledisableWorkflowNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsEnabledisableWorkflowForbiddenError - Access is forbidden.
type WorkflowsEnabledisableWorkflowForbiddenError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsEnabledisableWorkflowForbiddenError{}

func (e *WorkflowsEnabledisableWorkflowForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsEnabledisableWorkflowPaymentRequiredError - Client error
type WorkflowsEnabledisableWorkflowPaymentRequiredError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsEnabledisableWorkflowPaymentRequiredError{}

func (e *WorkflowsEnabledisableWorkflowPaymentRequiredError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsEnabledisableWorkflowUnauthorizedError - Access is unauthorized.
type WorkflowsEnabledisableWorkflowUnauthorizedError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsEnabledisableWorkflowUnauthorizedError{}

func (e *WorkflowsEnabledisableWorkflowUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsEnabledisableWorkflowBadRequestError - The server could not understand the request due to invalid syntax.
type WorkflowsEnabledisableWorkflowBadRequestError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsEnabledisableWorkflowBadRequestError{}

func (e *WorkflowsEnabledisableWorkflowBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
