// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// WorkflowsListWorkflowsGatewayTimeoutError - Server error
type WorkflowsListWorkflowsGatewayTimeoutError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsListWorkflowsGatewayTimeoutError{}

func (e *WorkflowsListWorkflowsGatewayTimeoutError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsListWorkflowsServiceUnavailableError - Service unavailable.
type WorkflowsListWorkflowsServiceUnavailableError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsListWorkflowsServiceUnavailableError{}

func (e *WorkflowsListWorkflowsServiceUnavailableError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsListWorkflowsBadGatewayError - Server error
type WorkflowsListWorkflowsBadGatewayError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsListWorkflowsBadGatewayError{}

func (e *WorkflowsListWorkflowsBadGatewayError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsListWorkflowsInternalServerError - Server error
type WorkflowsListWorkflowsInternalServerError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsListWorkflowsInternalServerError{}

func (e *WorkflowsListWorkflowsInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsListWorkflowsUnprocessableEntityError - Client error
type WorkflowsListWorkflowsUnprocessableEntityError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsListWorkflowsUnprocessableEntityError{}

func (e *WorkflowsListWorkflowsUnprocessableEntityError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsListWorkflowsConflictError - The request conflicts with the current state of the server.
type WorkflowsListWorkflowsConflictError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsListWorkflowsConflictError{}

func (e *WorkflowsListWorkflowsConflictError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsListWorkflowsNotFoundError - The server cannot find the requested resource.
type WorkflowsListWorkflowsNotFoundError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsListWorkflowsNotFoundError{}

func (e *WorkflowsListWorkflowsNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsListWorkflowsForbiddenError - Access is forbidden.
type WorkflowsListWorkflowsForbiddenError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsListWorkflowsForbiddenError{}

func (e *WorkflowsListWorkflowsForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsListWorkflowsPaymentRequiredError - Client error
type WorkflowsListWorkflowsPaymentRequiredError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsListWorkflowsPaymentRequiredError{}

func (e *WorkflowsListWorkflowsPaymentRequiredError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsListWorkflowsUnauthorizedError - Access is unauthorized.
type WorkflowsListWorkflowsUnauthorizedError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsListWorkflowsUnauthorizedError{}

func (e *WorkflowsListWorkflowsUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// WorkflowsListWorkflowsBadRequestError - The server could not understand the request due to invalid syntax.
type WorkflowsListWorkflowsBadRequestError struct {
	// Represents a single response containing data of type T.
	Meta     components.CommonV3ErrorMeta `json:"meta"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &WorkflowsListWorkflowsBadRequestError{}

func (e *WorkflowsListWorkflowsBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
